CREATE LOGIN [databasetasks] FROM EXTERNAL PROVIDER;
CREATE USER [databasetasks] FROM EXTERNAL PROVIDER;

GRANT ALTER ANY EVENT SESSION TO [databasetasks] --login, not user 

/* Sub-roles for SQL MI 
 https://techcommunity.microsoft.com/blog/sqlserver/new-granular-permissions-for-sql-server-2022-and-azure-sql-to-improve-adherence-/3607507 
CREATE ANY EVENT SESSION
DROP ANY EVENT SESSION
ALTER ANY EVENT SESSION 
ALTER ANY EVENT SESSION ADD EVENT
ALTER ANY EVENT SESSION DROP EVENT
ALTER ANY EVENT SESSION ENABLE
ALTER ANY EVENT SESSION DISABLE
ALTER ANY EVENT SESSION ADD TARGET
ALTER ANY EVENT SESSION DROP TARGET

*/